service: backend

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221


functions:
  app:
    handler: app.handler
    events:  
      - http: ANY /    
      - http: 'ANY /{proxy+}'

   